fix: update to Nerd Fonts 3 code points
nvim-tree/nvim-web-devicons pull request #264
Opened 2023-05-01 14:49 UTC by vlada-dudr

Nerd Fonts 3 changed code points of some icons, this updates it according  to table in [this comment](https://github.com/lifepillar/vim-colortemplate.git)

This will break everyone being on Nerd 2, but without it everyone on version 3 is broken also...

2023-05-01 16:34 UTC, Flygrounder commented
I believe, the proper way of handling this is adding an option in `setup`. I am not sure though, what should be the default: old version or new as probably most users have not yet upgraded to v3.

2023-05-01 17:49 UTC, eeeXun commented
Some icons didn't change to Nerd Font 3. [nerdfix](https://github.com/loichyan/nerdfix) may help.

2023-05-01 17:51 UTC, carlosala commented
I agree with @Flygrounder, it should be a flag. I'm personally using nf3, but most of the people will be for sure stuck for years in v2.

2023-05-02 07:46 UTC, luizkowalski commented
just weighing in: according to the [Finii from Nerd Font](https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1530999114), there should be a "translation" [database](https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287) (under details). I'm not sure if these would be backwards compatible to be honest. Does anyone know?

2023-05-02 07:55 UTC, carlosala commented
@luizkowalski I'd say there are icons (the ones https://www.nerdfonts.com/cheat-sheet) that are not marked as obsolete and are compatible for both versions.

2023-05-02 08:20 UTC, Finii commented
> there are icons [...] that are not marked as obsolete and are compatible for both versions

In my opinion it would always be better to not-use the Material Design Icons (also not the new ones), because they do not have a codepoint-stability guarantee, so with the next update the icon on codepoint X could be exchanged :roll_eyes: It does not happen often, but from time to time if you really compare their releases. Maybe by accident.
On the other hand, MDI has so many icons and if you want some very specific one there is only MDI that has it.

I think there is a document about the codepoint stability of the various sets: https://github.com/ryanoasis/nerd-fonts/issues/365#issuecomment-1254969225. As project I would prefer icons where upstream guarantees that their codepoints will not change.

2023-05-02 08:39 UTC, carlosala commented
@Finii the problem is what you pointed out. MD added now 7k icons, that are probably quite unique and not replaceable

2023-05-02 08:56 UTC, Finii commented
:+1: And I always check (and try to fix if needed) codepoint stability on any upstream update (see for example the [octicons update](https://github.com/ryanoasis/nerd-fonts/pull/1156) where Nerd Fonts introduces a codepoint stability where there was none upstream).

2023-05-02 09:02 UTC, vlada-dudr commented
@luizkowalski: that's what I used to convert.

I was thinking to wrap translation table into lua, but it seemed wasteful to include table of ~1600 entries.

I am curious how implement two sets of icons. I see options:
1) embedding translation table and when icon is requested do translation
2) adding extra field into icon definitions  for second icon option
3) make second set of whole icon definition

I am in favour of 3) - easy to drop, easy to generate through translation table from original table in make script.

2023-05-02 12:58 UTC, rootex- commented
> Some obsoleted icons didn't change. [nerdfix](https://github.com/loichyan/nerdfix) may help.

thanks, nerdfix did help 🤝

2023-05-02 18:09 UTC, luizkowalski commented
> > Some obsoleted icons didn't change. [nerdfix](https://github.com/loichyan/nerdfix) may help.
> 
> thanks, nerdfix did help 🤝

@rootex- mind to share how you did it? I tried nerdfix but it is not working for some reason...

2023-05-02 18:32 UTC, mehalter commented
It's also worth noting that the new locations of the material design icons (`nf-md-X`) are also available in Nerd Fonts v2 with v2.3+. The breaking change that came with v3 simply removed the old locations that were going to be deprecated. So migrating these icons (`nf-mdi-X` to `nf-md-X`) will maintain compatibility with the latest v2 and v3. Granted this will not support <v2.3, so I would agree that having a flag for legacy support would be a good idea but keeping the default as using the new v3 icon locations.

2023-05-02 18:34 UTC, mehalter commented
You could also just add a comment on the `README` with the last commit that supported Nerd Fonts v2 which people can use it if they don't want to install (or can't install) Nerd Fonts v3 for whatever reason. It just depends on if you want to continuously maintain support for v2 as new features get added to `nvim-web-devicons`.

2023-05-03 05:13 UTC, rootex- commented
> > > Some obsoleted icons didn't change. [nerdfix](https://github.com/loichyan/nerdfix) may help.
> > 
> > 
> > thanks, nerdfix did help 🤝
> 
> @rootex- mind to share how you did it? I tried nerdfix but it is not working for some reason...

To discover all obsolete symbols in a file:
```
$ nerdfix check <filename>
note: Found obsolete icon U+F722
  ┌─ filename:1:9
  │
1 │ icon = "",
  │         ^ Icon 'nf-mdi-file_music' is marked as obsolete
  │
  = You could replace it with:
        1. 󰈣 U+F0223 nf-md-file_music
        2. 󰝚 U+F075A nf-md-music
        3. 󰸪 U+F0E2A nf-md-file_music_outline
        4. 󱝟 U+F175F nf-md-archive_music
...
...
...
```

To fix every obsolete symbol
```
$ nerdfix fix <filename>
// prints a prompt for every symbol
note: Found obsolete icon U+F722
  ┌─ filename:1:9
  │
1 │ icon = "",
  │         ^ Icon 'nf-mdi-file_music' is marked as obsolete
  │
  = You could replace it with:
        1. 󰈣 U+F0223 nf-md-file_music
        2. 󰝚 U+F075A nf-md-music
        3. 󰸪 U+F0E2A nf-md-file_music_outline
        4. 󱝟 U+F175F nf-md-archive_music

? Input an icon:
  1
  2
  3
  4
[(Tab) to autocomplete, (Esc) to cancel, (Ctrl-C) to abort]
```

2023-05-03 06:57 UTC, vlada-dudr commented
Thinking about it more, maybe it is ok to merge it. Nerd fonts released version 2.3 earlier this year and deprecated now dropped code points. There are two solutions for people on <=2.2: install newer version (easy), pin commit (easy). Let's just make sure people know what's going on.

2023-05-03 07:01 UTC, vlada-dudr commented
I updated readme and reworded commit so it contains exclamation mark

2023-05-03 15:47 UTC, carlosala commented
Agree

2023-05-03 18:29 UTC, vlada-dudr commented
Or maybe let's tag (or branch?) that commit so it is more explicit?

2023-05-03 20:38 UTC, tapayne88 commented
Apologies for interrupting your conversation but I _think_ this PR might be missing some icons. When I've run nerdfix locally I've found the following also need updating
- `.babelrc`
- `json5`
- `pdf`
- `log`

Could just be my version of nerdfont and/or nerdfix though! 😅

2023-05-03 21:10 UTC, vlada-dudr commented
@tapayne88 you can pull request my master if you wish ;)

2023-05-03 22:20 UTC, tapayne88 commented
> @tapayne88 you can pull request my master if you wish ;)

Hopefully this should do it - https://github.com/vlada-dudr/nvim-web-devicons/pull/1 🤞

2023-05-04 10:27 UTC, vlada-dudr commented
@tapayne88, so I merged it into my branch.

Now tell me who can move it forward...

2023-05-05 22:45 UTC, gegoune commented
I'll try to review tomorrow. 

Thanks to everyone involved!

2023-05-06 04:17 UTC, alex-courtis approved these changes
Many thanks for the quick fix!

All changes appear to be mdi ->md which is the most straightforward and correct migration.

RE compatibility: providing setup option / both sets is unnecessary complexity.

A `nerd-fonts-2` tag along with documentation / readme should be sufficient, pending @gegoune approval.

2023-05-06 07:20 UTC, gegoune requested changes
Couple of nitpicks regarding read me update.

Thanks again!

2023-05-06 07:20 UTC, gegoune commented on README.md
> +# Warning
```suggestion
# Notice
```

Perhaps that sounds better?

2023-05-06 07:20 UTC, gegoune commented on README.md
> +Nerd fonts moved some symbols with version 3.0, version 2.3 is meant for transition. Nvim-web-devicons will now work with only with version 2.3+
```suggestion
Nerd fonts moved some symbols with version 3.0. Version 2.3 is meant for transition, supporting both version 2 and version 3 icons. 

Nvim-web-devicons requires version 2.3 or above to work properly. If you are unable to update please use your plugin manager to pin version of nvim-web-dev icons to `nerd-v2-compat` tag.
```

2023-05-06 07:37 UTC, vlada-dudr commented on README.md
> +Nerd fonts moved some symbols with version 3.0, version 2.3 is meant for transition. Nvim-web-devicons will now work with only with version 2.3+
Thanks, I that's what I needed ;)

2023-05-06 07:37 UTC, vlada-dudr commented on README.md
> +# Warning
done

2023-05-06 08:38 UTC, gegoune approved these changes

2023-05-06 08:47 UTC, gegoune commented
I have just pushed aforementioned compat tag pointing to current master.

2023-05-07 00:53 UTC, alex-courtis approved these changes
Many thanks @vlada-dudr et al for the quick turnaround!

2023-05-07 00:54 UTC, merged

2023-05-10 22:17 UTC, Redyf commented
> @luizkowalski
> 
> > > > Some obsoleted icons didn't change. [nerdfix](https://github.com/loichyan/nerdfix) may help.
> > > 
> > > 
> > > thanks, nerdfix did help handshake
> > 
> > 
> > @rootex- mind to share how you did it? I tried nerdfix but it is not working for some reason...
> 
> To discover all obsolete symbols in a file:
> 
> ```
> $ nerdfix check <filename>
> note: Found obsolete icon U+F722
>   ┌─ filename:1:9
>   │
> 1 │ icon = "",
>   │         ^ Icon 'nf-mdi-file_music' is marked as obsolete
>   │
>   = You could replace it with:
>         1. 󰈣 U+F0223 nf-md-file_music
>         2. 󰝚 U+F075A nf-md-music
>         3. 󰸪 U+F0E2A nf-md-file_music_outline
>         4. 󱝟 U+F175F nf-md-archive_music
> ...
> ...
> ...
> ```
> 
> To fix every obsolete symbol, input a number or search symbols with autocompletion:
> 
> ```
> $ nerdfix fix <filename>
> // prints a prompt for every symbol
> note: Found obsolete icon U+F722
>   ┌─ filename:1:9
>   │
> 1 │ icon = "",
>   │         ^ Icon 'nf-mdi-file_music' is marked as obsolete
>   │
>   = You could replace it with:
>         1. 󰈣 U+F0223 nf-md-file_music
>         2. 󰝚 U+F075A nf-md-music
>         3. 󰸪 U+F0E2A nf-md-file_music_outline
>         4. 󱝟 U+F175F nf-md-archive_music
> 
> ? Input an icon:
>   1
>   2
>   3
>   4
> [(Tab) to autocomplete, (Esc) to cancel, (Ctrl-C) to abort]
> ```

This was really helpful, thanks!