fix: fixed icon of vue
nvim-tree/nvim-web-devicons pull request #266
Opened 2023-05-04 10:59 UTC by jfbeatit

Fix reason: I use the font `SauceCodePro Nerd Font Mono `, after i update this plugin to the latest version, the vue icon can not display anymore.

2023-05-05 13:42 UTC, gegoune commented
Try updading your font instead, this icon has been recently changed to more accurate one.

2023-05-06 04:21 UTC, alex-courtis commented
Let's merge #264 first

2023-05-06 07:32 UTC, gegoune commented
Not sure we want to merge this one, Alex. Vue icon has been very recently updated to one that's reverted here.

If we are using proper icons that are only available in recent font versions we will endlessly get requests like this while solution is to update fonts. 

We will shortly provide compat tag for version 2 icons. That might solve the issue this pr tries to address.

Or we should come up with proper policy on how we handle those things.

2023-05-07 00:57 UTC, alex-courtis requested changes

2023-05-07 00:57 UTC, alex-courtis commented on lua/nvim-web-devicons.lua
> +    icon = "﵂",
Unfortunately this is a nerd font v2 icon; we need a v3 icon.

See #264

You'll need to run nerdfix.

2023-05-07 01:04 UTC, alex-courtis commented
> Not sure we want to merge this one, Alex. Vue icon has been very recently updated to one that's reverted here.
> 
> If we are using proper icons that are only available in recent font versions we will endlessly get requests like this while solution is to update fonts.

It looks like the vue icon on master is the correct v3 icon.

> We will shortly provide compat tag for version 2 icons. That might solve the issue this pr tries to address.
> 
> Or we should come up with proper policy on how we handle those things.

The tag should be enough.

I have Hack Nerd Font Mono set as my browser font, so I can quickly see in the PR whether the icon is a valid (v3) icon.

2023-05-07 01:06 UTC, alex-courtis commented
> Or we should come up with proper policy on how we handle those things.

We _could_ maintain a v2 branch rather than a tag, for reverting v3->v2 icons.

That's a lot of work and the branches will completely diverge.

2023-05-07 01:07 UTC, alex-courtis commented
Optimistically closing: @jfbeatit can you please update your font to v3 and test again.

We'll reopen if that doesn't work.

2023-05-07 01:07 UTC, closed without merging