feat: support icons_by_file_extension
nvim-tree/nvim-web-devicons pull request #370
Opened 2023-12-31 11:29 UTC by BBboy01

Closes #168

2023-12-31 11:42 UTC, BBboy01 commented
`make colors` makes me delete `icons_by_file_prefix` table in `lua/nvim-web-devicons/icons-light.lua`, but this will occur an exception no icons show after set `vim.o.background = "light"`, how can i fix this? If there are something i missed, let me know plz.

2024-01-06 01:25 UTC, alex-courtis requested changes
I've gone cold on this one; it's introducing breaking changes.

We need to refactor this change - specifically the API - such that existing behaviour does not change. For the user to return the prefix icon they will need to explicitly specify it.

Unfortunately we haven't used named parameters for all API methods however we cannot change that. `options` is available in some cases but not all.

Proposal:
Draft an API that preserves existing behaviour and allows prefixes to be selected.

Extension:
New API that uses all name parameters via `options`

2024-01-06 01:25 UTC, alex-courtis commented on README.md
> +require'nvim-web-devicons'.get_icon(filename, pre_or_ext, options)
This will break existing behaviour - a prefixed icon will be returned where none was before.

2024-01-06 01:25 UTC, alex-courtis commented on lua/nvim-web-devicons.lua
> +      or get_icon_by_prefix(name, pre_or_ext, opts)
This will result in a prefix being returned when users were previously expecting an extension, when the key is the same.

2024-03-02 02:35 UTC, alex-courtis commented
Please reopen if you wish to continue this change.

2024-03-02 02:35 UTC, closed without merging