Add checkhealth
nvim-tree/nvim-web-devicons pull request #403
Opened 2024-02-21 21:13 UTC by BoltsJ

2024-02-24 02:53 UTC, alex-courtis requested changes

2024-02-24 22:07 UTC, BoltsJ commented on lua/nvim-web-devicons.lua
> +  ["checkhealth"] = "checkhealth",
My mistake. I thought it was a mapping for the `filetype` option. The filename is `health://` and the filetype is `checkhealth`,

2024-02-25 01:55 UTC, alex-courtis commented on lua/nvim-web-devicons.lua
> +  ["checkhealth"] = "checkhealth",
You're right - it is for filetype.

Apologies, I didn't look at both.

2024-02-25 01:55 UTC, alex-courtis approved these changes
Many thanks for your contribution!

2024-02-25 01:56 UTC, merged