feat: add mp3 file icons
nvim-tree/nvim-web-devicons pull request #410
Opened 2024-03-03 22:07 UTC by pauchiner

2024-03-05 22:07 UTC, alex-courtis requested changes
Looking good; let's add the rest https://github.com/nvim-tree/nvim-web-devicons/issues/404#issuecomment-1975375731

2024-03-07 03:40 UTC, alex-courtis requested changes
These are looking good, however they should actually be in the `icons_by_file_extension` table.

There are already some of these extensions in there... including mp3.

I'll be grateful if you could move the new ones in there, overwriting.

However... the existing ones are using `nf-fa-music`. We'll need to use that one, to avoid a breaking change.

2024-03-07 10:06 UTC, pauchiner commented
Sorry, I made those commits in a few free minutes yesterday, I didn't notice either the `extensions table` or the `breaking changes`, I'm already working on fixing it.

2024-03-09 02:04 UTC, alex-courtis commented
Looking good: `:NvimWebDeviconsHiTest`

However I think we might be backwards here: all the new icons are in `icons_by_filename` wheras they should be in `icons_by_file_extension`. The user will be finding music file icons via `get_icon` with an extension rather than matching an exact file name.

The `filetypes` will still correctly map to `icons_by_file_extension`.

2024-04-07 03:28 UTC, alex-courtis commented
Any updates @pauchiner ? This is really close...

2024-04-08 11:30 UTC, pauchiner commented
Sorry, I was absent due to personal things, as soon as I can I will make a commit with the changes.

2024-04-09 02:15 UTC, alex-courtis requested changes
Looking good, a couple of tidies needed.

2024-04-09 02:15 UTC, alex-courtis commented on lua/nvim-web-devicons/icons-default.lua
> +  },
Please remove - it's present in extensions.

2024-04-09 02:15 UTC, alex-courtis commented on lua/nvim-web-devicons.lua
> +  ["wma"] = "wma",
The above aren't vim filetypes so should not be mapped to extensions.

2024-04-16 05:59 UTC, alex-courtis requested changes
Still not quite there...

None of these file types correspond to vim syntax filetypes, see `/usr/share/nvim/runtime/syntax`

We need to remove them from the mapping
```lua
-- Map of filetypes -> icon names
local filetypes = {
```

2024-04-19 15:48 UTC, pauchiner commented
So if aren't vim filetypes, how are mapped?
I think im not understanding your point, Sorry.

2024-04-20 06:55 UTC, alex-courtis commented
> So if aren't vim filetypes, how are mapped? I think im not understanding your point, Sorry.

No worries; this is not very clear from the names.

Files like these are simply mapped by their extension against the keys of `icons_by_file_extension`. There's no need for any extra mapping.

Try
```
:lua print(require("nvim-web-devicons").get_icon("aiff"))
```

2024-04-21 00:52 UTC, hasecilu commented
I'm not really sure if [PCM](https://en.wikipedia.org/wiki/Pulse-code_modulation) file extension is really used, so could be added.

2024-04-23 09:19 UTC, pauchiner commented
I have already deleted the filetypes that I added at the time, but then by the same logic, those that were previously there should also be deleted, such as mp3, mp4, wav...

2024-04-28 01:21 UTC, alex-courtis commented
> I have already deleted the filetypes that I added at the time, but then by the same logic, those that were previously there should also be deleted, such as mp3, mp4, wav...

Good catch! Yes, they should be removed.

In the interest of speed, I'll push that change to this branch.

2024-04-28 01:28 UTC, alex-courtis commented
> I'm not really sure if [PCM](https://en.wikipedia.org/wiki/Pulse-code_modulation) file extension is really used, so could be added.

Sounds good! Any others you think of please do raise a PR...

2024-04-28 01:28 UTC, alex-courtis approved these changes

2024-04-28 01:28 UTC, alex-courtis approved these changes
Many thanks for your contribution and many thanks for bearing with all the back and forth.

2024-04-28 01:29 UTC, merged