fix: update .bablerc icon and tsx,jsx colors
nvim-tree/nvim-web-devicons pull request #472
Opened 2024-06-07 10:29 UTC by ronitkrshah

The changes in the PR would update icon for `.bablerc` file and React File colors

- Update babelrc icon to `nf-seti-babel` (e639)

To diiferenciate between `jsx` and `tsx` files.  Changed `jsx` color to **yellow**. Because it will be easier to work with js and jsx files. TSX color changed to Previous JSX color

## Previous JSX with JS
![Screenshot from 2024-06-07 15-55-15](https://github.com/nvim-tree/nvim-web-devicons/assets/118371892/afeaa4b5-9f9e-4e4a-9cf1-d6c1b79a3b14)

## After Changing Colors
![Screenshot from 2024-06-07 15-56-15](https://github.com/nvim-tree/nvim-web-devicons/assets/118371892/589bb481-8d47-47a6-abce-0355895510f3)

2024-06-08 06:05 UTC, alex-courtis commented
VSCode ref:
![20240608_160422](https://github.com/nvim-tree/nvim-web-devicons/assets/1505378/bcacb876-723b-497a-a645-be0cd5c04365)

2024-06-08 06:08 UTC, alex-courtis requested changes
We've been going back and forth on the js / ts colours too many times. A proper overhaul with seti/md themes is underway; let's wait for that please.

Babel looks great!

2024-06-08 09:37 UTC, ronitkrshah commented
Reverted jsx & tsx

2024-06-09 00:56 UTC, alex-courtis commented
> Reverted jsx & tsx

Many thanks, sorry for the trouble.

2024-06-09 00:56 UTC, alex-courtis approved these changes
Many thanks for the contribution!

2024-06-09 00:57 UTC, merged