Gleam: move from icons_by_filename to icons_by_file_extension
nvim-tree/nvim-web-devicons pull request #485
Opened 2024-07-23 10:54 UTC by Massolari

According to the documentation
> There are two tables where icons can be added:
> 1. icons_by_filename
> 2. icons_by_file_extension
>
> Add the icon in table 1. if the icon is for a file that is always named that
> way, for example `.gitconfig`. Add to table 2. if the icon is for all files
> with an extension.

the Gleam icon must be placed under `icons_by_file_extension`

Disclaimer: it was not working for me and that's the reason

2024-07-27 02:56 UTC, alex-courtis requested changes
Let's leave it in `icons_by_filename` please; it may break some users...

2024-07-27 07:38 UTC, Massolari commented
I can do that.
But it doesn't make sense. In Gleam, there is no file called `.gleam`

2024-07-28 02:56 UTC, alex-courtis commented
> I can do that. But it doesn't make sense. In Gleam, there is no file called `.gleam`

Please accept my apologies; I misread as filetype...

2024-07-28 02:57 UTC, alex-courtis approved these changes
Many thanks for your contribution!

2024-07-28 02:57 UTC, merged