feat: add http
nvim-tree/nvim-web-devicons pull request #497
Opened 2024-09-19 12:07 UTC by mawkler

Feel free to change the icon and/or colors. I picked the colors from [this logo on wikipedia](https://en.wikipedia.org/wiki/HTTP?oldformat=true#/media/File:HTTP_logo.svg). I'm not sure how established it is though.

2024-09-20 02:05 UTC, alex-courtis commented
Colours look good dark:
![20240920_120442](https://github.com/user-attachments/assets/09a9cf74-dc6c-4849-bb1f-37f73574f4c4)

and light:
![20240920_120503](https://github.com/user-attachments/assets/b1575e38-ad90-4040-8a52-67f4f695c627)

2024-09-20 02:09 UTC, alex-courtis requested changes
I'm not quite sure of the use case, but this looks good.

Build https://github.com/nvim-tree/nvim-web-devicons/actions/runs/10942703932/job/30409605842?pr=497 is failing due to a light colour mismatch.

The light versions are all generated, please use the tool https://github.com/nvim-tree/nvim-web-devicons/blob/master/CONTRIBUTING.md#generate-colors

2024-09-20 02:09 UTC, alex-courtis commented on lua/nvim-web-devicons/icons-default.lua
> +  },
http is not an operating system.

Please move to `icons_by_file_extension`

2024-09-20 07:21 UTC, mawkler commented
@alex-courtis 

> I'm not quite sure of the use case

It is for files containing HTTP requests. They can be used with HTTP clients like [rest.nvim](https://github.com/rest-nvim/rest.nvim) or [kulala.nvim](https://github.com/mistweaverco/kulala.nvim/).

I have now auto generated the light colors 🙂

2024-09-21 00:03 UTC, alex-courtis approved these changes
Many thanks for your contribution!

2024-09-21 00:04 UTC, merged